In [1]:
!pip install simpletransformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.5/315.5 kB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 7.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 16.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 34.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 67.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 31.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.3/277.3 kB 38.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 18.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 28.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 22.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.2/401.2 

In [2]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-m

In [3]:
import logging
import pandas as pd
from simpletransformers.seq2seq import Seq2SeqModel, Seq2SeqArgs
import string
from sklearn.model_selection import train_test_split

In [4]:
logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

In [5]:
df = pd.read_csv("train.csv")
df.drop(['Context'], axis = 1, inplace = True)
df

Response
0     If everyone thinks you're worthless, then mayb...
1     Hello, and thank you for your question and see...
2     First thing I'd suggest is getting the sleep y...
3     Therapy is essential for those that are feelin...
4     I first want to let you know that you are not ...
...                                                 ...
3507  Absolutely not! It is never in a child's best ...
3508  I'm sorry you have tension between you and you...
3509  The true answer is, "no one can really say wit...
3510  How do you help yourself to believe you requir...
3511                           hmm this is a tough one!

[3512 rows x 1 columns]

In [6]:
df = df.dropna()
df = df.drop_duplicates()

In [7]:
def remove_punctuation(text):
    translator = str.maketrans('', '', string.punctuation)
    return text.translate(translator)
new_data = {'input_text': [], 'target_text': []}

for index, row in df.iterrows():
    input_text = remove_punctuation(row['Response'])  # Remove punctuation for input
    target_text = row['Response']
    new_data['input_text'].append(input_text)
    new_data['target_text'].append(target_text)

new_df = pd.DataFrame(new_data)

In [8]:
new_df

input_text  \
0     If everyone thinks youre worthless then maybe ...   
1     Hello and thank you for your question and seek...   
2     First thing Id suggest is getting the sleep yo...   
3     Therapy is essential for those that are feelin...   
4     I first want to let you know that you are not ...   
...                                                 ...   
2474  Being in this position is tough If seeking ano...   
2475  It sounds like you are on the right track Reco...   
2476  HelloIt sounds like you are really concerned a...   
2477  Hi  This is an excellent question    I think t...   
2478                            hmm this is a tough one   

                                            target_text  
0     If everyone thinks you're worthless, then mayb...  
1     Hello, and thank you for your question and see...  
2     First thing I'd suggest is getting the sleep y...  
3     Therapy is essential for those that are feelin...  
4     I first want to let you know that you are not ...  
...                                                 ...  
2474  Being in this position is tough. If seeking an...  
2475  It sounds like you are on the right track. Rec...  
2476  Hello.It sounds like you are really concerned ...  
2477  Hi.  This is an excellent question !   I think...  
2478                           hmm this is a tough one!  

[2479 rows x 2 columns]

In [9]:
new_df.rename(columns={'train_X':'input_text','train_y':'target_text'},inplace=True)
train_df,eval_df=train_test_split(new_df,test_size=0.1)

In [10]:
model_args = Seq2SeqArgs()
model_args.num_train_epochs = 1
model_args.evaluate_generated_text = True
model_args.evaluate_during_training = True
model_args.evaluate_during_training_verbose = True
model_args.overwrite_output_dir=True
model_args.max_length=300
model_args.task_specific_params=None

In [11]:
model = Seq2SeqModel(
    encoder_decoder_type="bart",
    encoder_decoder_name="facebook/bart-large",
    args=model_args,

)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.63k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.02G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [12]:
model.train_model(train_df, eval_data=eval_df)

/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()


  0%|          | 0/2231 [00:00<?, ?it/s]

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 1 of 1:   0%|          | 0/279 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:143: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0, 'forced_eos_token_id': 2}
Some non

  0%|          | 0/248 [00:00<?, ?it/s]

Generating outputs:   0%|          | 0/3 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:535: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:554: UserWarning: `num_beams` is set to 1. However, `length_penalty` is set to `2.0` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.
  warnings.warn(
Some non-default generation parameters are set in the model config. These should go into a GenerationConfig file (https://huggingface.co/docs/transformers/generation_strategies#save-a-custom-decoding-strategy-with-your-model) instead. This warning will be raised to an exception in v4.41.
Non-default generation parameters: {'early_stopping': True, 'num_beams': 4, 'no_repeat_ngram_size': 3, '

(279,
 {'global_step': [279],
  'eval_loss': [0.18009439607461294],
  'train_loss': [0.16327977180480957]})

In [13]:
result = model.eval_model(eval_df)

/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()


  0%|          | 0/248 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/3 [00:00<?, ?it/s]

Generating outputs:   0%|          | 0/3 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:535: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:554: UserWarning: `num_beams` is set to 1. However, `length_penalty` is set to `2.0` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.
  warnings.warn(


In [14]:
eval_predict=model.predict(list(eval_df['input_text'].values))

Generating outputs:   0%|          | 0/3 [00:00<?, ?it/s]

In [15]:
eval_df['input_text'][:]

1475    It is completely understandable that you are s...
469     Why not accept and tolerate that you naturally...
375     It’s very normal to be nervous going into ther...
2099    Depending on your area and location there may ...
1980    Most counselors are very approachable and many...
                              ...                        
197     It is hard to make a definite diagnosis howeve...
1026    That sounds like a very hurtful situation Unfo...
2009    I suggest that you work on emotional awareness...
1916    Absolutely its normal to cry in therapy sessio...
1230    I dont think theres anything that youre suppos...
Name: input_text, Length: 248, dtype: object

In [16]:
eval_predict[:1]

["It is completely understandable that you are struggling to forgive and forget this betrayal and I'd like to echo the sentiment of Danielle Alvarez, infidelity takes time to heal from so allow yourself to grieve and find the support you need. I'd highly suggest going to couples therapy and addressing all the issues that Danielle raised, especially whether he has expressed genuine remorse and is being completely transparent with you and is taking responsibility for the choice he made, including acknowledging the immense impact it had on you, your relationship and your ability to trust him.\xa0If you have doubts about being able to trust"]

In [17]:
test_df = pd.read_csv("testing.csv")

In [18]:
print(test_df)

                                             Testing
0  Players dash across lush green fields sweat gl...


In [19]:
to_test=test_df['Testing'].values.tolist()

In [20]:
model.predict(to_test)

Generating outputs:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:535: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:554: UserWarning: `num_beams` is set to 1. However, `length_penalty` is set to `2.0` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.
  warnings.warn(


['Players dash across lush green fields, sweat glistening under stadium lights, fans roar with passion, goals electrify the air, teamwork orchestrates victory, coaches strategize on sidelines, adrenaline fuels every kick, dreams soar on wings of determination, football unites nations, a beautiful game where moments become legends and the world watches in awe.']

In [21]:
!pip install SpeechRecognition

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.8/32.8 MB 21.3 MB/s eta 0:00:00


In [23]:
import speech_recognition as sr

In [ ]:
def audio_to_text(audio_file):
    recognizer = sr.Recognizer()
    with sr.AudioFile(audio_file) as source:
        audio_data = recognizer.record(source)
        text = recognizer.recognize_google(audio_data)
    return text

In [25]:
def transcribe_audio(filename):
    # create a speech recognition object
    r = sr.Recognizer()

    # use the audio file as the audio source
    with sr.AudioFile(filename) as source:
        audio = r.record(source)

    # try to recognize the speech in the recording
    try:
        return r.recognize_google(audio)
    except sr.UnknownValueError:
        return "Google Speech Recognition could not understand your audio"
    except sr.RequestError as e:
        return "Could not request results from Google Speech Recognition service; {0}".format(e)

In [26]:
audio_file = "harvard.wav"
audio_text = transcribe_audio(audio_file)

In [27]:
audio_predictions = model.predict([audio_text])

Generating outputs:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:535: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:554: UserWarning: `num_beams` is set to 1. However, `length_penalty` is set to `2.0` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.
  warnings.warn(


In [28]:
print("Audio Input Text:", audio_text)
print("Predictions:", audio_predictions)

Audio Input Text: the stale smell of old beer lingers it takes heat to bring out the odor a cold dip restores health and zest a salt pickle taste fine with ham tacos al pastor are my favorite a zestful food is the hot cross bun
Predictions: ['the stale smell of old beer lingers, it takes heat to bring out the odor, a cold dip restores health and zest, a salt pickle taste fine with ham tacos, al pastor are my favorite, a zestful food is the hot cross bun.']


In [34]:
def capitalize_sentences(text):
    sentences = text.split('. ')  # Split text into sentences
    capitalized_sentences = [sentence.capitalize() for sentence in sentences]  # Capitalize each sentence
    return '. '.join(capitalized_sentences)

In [ ]:
audio_text_capitalize = transcribe_audio(audio_file)

In [36]:
audio_text_capitalize = capitalize_sentences(audio_text)  # Capitalize sentences
audio_predictions_capitalize = model.predict([audio_text_capitalize])

Generating outputs:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:535: UserWarning: `num_beams` is set to 1. However, `early_stopping` is set to `True` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `early_stopping`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:554: UserWarning: `num_beams` is set to 1. However, `length_penalty` is set to `2.0` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.
  warnings.warn(


In [37]:
print("Audio Input Text:", audio_text_capitalize)
print("Predictions:", audio_predictions_capitalize)

Audio Input Text: The stale smell of old beer lingers it takes heat to bring out the odor a cold dip restores health and zest a salt pickle taste fine with ham tacos al pastor are my favorite a zestful food is the hot cross bun
Predictions: ['The stale smell of old beer lingers, it takes heat to bring out the odor, a cold dip restores health and zest, a salt pickle taste fine with ham tacos, al pastor are my favorite, a zestful food is the hot cross bun.']


In [38]:
!pip install scikit-learn

In [39]:
from sklearn.metrics import confusion_matrix, classification_report

In [40]:
actual_labels = eval_df['target_text'].tolist()
predicted_labels = [pred[0] for pred in eval_predict]

In [42]:
print("Confusion Matrix:")
print(confusion_matrix(actual_labels, predicted_labels))
print("\nClassification Report:")
print(classification_report(actual_labels, predicted_labels))

Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]

Classification Report:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.